version: '3'
services: 
  mysql_db:
    build:
      dockerfile: ./mysql.dockerfile
      context: .
    image: fabioj/mysql_vacancy_matching
    container_name: mysql-db-container
    ports:
      - "3306:3306"
    networks:
      - spring-network
      
  graph-dijkstra-rest-container:
    build:
      context: .
      dockerfile: ./spring.dockerfile
    image: fabioj/graph-dijkstra-rest
    container_name: graph-dijkstra-rest-container
    ports: 
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - "mysql_db"
      
networks:
  spring-network: