CREATE TABLE COMPANY
   ("ID_COMPANY" NUMBER auto_increment,  
	"JOB_TITLE" VARCHAR2(50 CHAR), 
	"JOB_DESCRIPTION" VARCHAR2(50 CHAR), 
	"JOB_LOCATION" VARCHAR2(50 CHAR), 
	"JOB_LEVEL" NUMBER(1,0), 
	PRIMARY KEY (ID_COMPANY)
   );
   
CREATE TABLE CANDIDATE
   ("ID_CANDIDATE" NUMBER auto_increment,  
	"CANDIDATE_NAME" VARCHAR2(50 CHAR), 
	"CANDIDATE_OCCUPATION" VARCHAR2(50 CHAR), 
	"CANDIDATE_LOCATION" VARCHAR2(50 CHAR), 
	"CANDIDATE_LEVEL" NUMBER(1,0),
	"CANDIDATE_APP_POSITION" VARCHAR2(50 CHAR),
	PRIMARY KEY (ID_CANDIDATE)
   );

CREATE TABLE RANKING
   ("ID_CANDIDATE_RANKED" NUMBER auto_increment,  
	"CANDIDATE_NAME" VARCHAR2(50 CHAR), 
	"CANDIDATE_OCCUPATION" VARCHAR2(50 CHAR), 
	"CANDIDATE_LOCATION" VARCHAR2(50 CHAR), 
	"CANDIDATE_LEVEL" NUMBER(1,0),
	"CANDIDATE_SCORE" VARCHAR2(50 CHAR),
	PRIMARY KEY (ID_CANDIDATE_RANKED)
   );

